version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
      - chmod +x scripts/start_server.sh
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo no Build phase...
artifacts:
  files:
    - app.js
    - package.json
    - node_modules/**
